export const levelUp = [
    {levelTxt: 'Rookie I', level: 1, requiredXp: 200 },
    {levelTxt: 'Rookie II',  level: 2, requiredXp: 400 },
    {levelTxt: 'Rookie III', level: 3, requiredXp: 600 },
    {levelTxt: 'Rookie IV',  level: 4, requiredXp: 800 },
    {levelTxt: 'Rookie V', level: 5, requiredXp: 1000 },
    {levelTxt: 'Veteran I', level: 6, requiredXp: 1200 },
    {levelTxt: 'Veteran II', level: 7, requiredXp: 1400 },
    {levelTxt: 'Veteran III', level: 8, requiredXp: 1600 },
    {levelTxt: 'Veteran IV', level: 9, requiredXp: 1800 },
    {levelTxt: 'Veteran V', level: 10, requiredXp: 2000 },
    {levelTxt: 'Elite I', level: 11, requiredXp: 2200 },
    {levelTxt: 'Elite II', level: 12, requiredXp: 2400 },
    {levelTxt: 'Elite III', level: 13, requiredXp: 2600 },
    {levelTxt: 'Elite IV', level: 14, requiredXp: 2800 },
    {levelTxt: 'Elite V', level: 15, requiredXp: 3000 },
    {levelTxt: 'Pro I', level: 16, requiredXp: 3200 },
    {levelTxt: 'Pro II', level: 17, requiredXp: 3400 },
    {levelTxt: 'Pro III', level: 18, requiredXp: 3600 },
    {levelTxt: 'Pro IV', level: 19, requiredXp: 3800 },
    {levelTxt: 'Pro V', level: 20, requiredXp: 4000 },
    {levelTxt: 'Master', level: 21, requiredXp: 4200 },
    {levelTxt: 'Master', level: 22, requiredXp: 4400 },
    {levelTxt: 'Master', level: 23, requiredXp: 4600 },
    {levelTxt: 'Master', level: 24, requiredXp: 4800 },
    {levelTxt: 'Master', level: 25, requiredXp: 5000 },
    {levelTxt: 'GrandMaster', level: 26, requiredXp: 5200 },
    {levelTxt: 'GrandMaster', level: 27, requiredXp: 5400 },
    {levelTxt: 'GrandMaster', level: 28, requiredXp: 5600 },
    {levelTxt: 'GrandMaster', level: 29, requiredXp: 5800 },
    {levelTxt: 'GrandMaster', level: 30, requiredXp: 6000 },
    {levelTxt: 'GrandMaster', level: 31, requiredXp: 6200 },
    {levelTxt: 'GrandMaster', level: 32, requiredXp: 6400 },
    {levelTxt: 'GrandMaster', level: 33, requiredXp: 6600 },
    {levelTxt: 'GrandMaster', level: 34, requiredXp: 6800 },
    {levelTxt: 'GrandMaster', level: 35, requiredXp: 7000 },
    {levelTxt: 'Legend', level: 36, requiredXp: 7200 },
    {levelTxt: 'Legend', level: 37, requiredXp: 7400 },
    {levelTxt: 'Legend', level: 38, requiredXp: 7600 },
    {levelTxt: 'Legend', level: 39, requiredXp: 7800 },
    {levelTxt: 'Legend', level: 40, requiredXp: 8000 },
];

export const Rankings = [
    {rank: 'Bronze', correctQestions: 3},
    {rank: 'Silver', correctQestions: 5},
    {rank: 'Gold', correctQestions: 10},
    {rank: 'Platinum', correctQestions: 13},
    {rank: 'Diamond', correctQestions:  15},
    {rank: 'Crimson', correctQestions: 20},
    {rank: 'Iridescent', correctQestions: 30},
];

export const prestigesStage = [
    {prestige: 1, requiredXp: 8000},
    {prestige: 2, requiredXp: 16000},
    {prestige: 3, requiredXp: 24000},
    {prestige: 4, requiredXp: 32000},
    {prestige: 5, requiredXp: 40000},
    {prestige: 6, requiredXp: 48000},
    {prestige: 7, requiredXp: 56000},
]
